name: Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CACHE: true

jobs:
  changes:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      any: ${{ steps.changes.outputs.any }}
      programs: ${{ steps.changes.outputs.programs }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Detect changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: .github/file-filters.yml

  build_programs:
    name: Programs
    if: ${{ needs.changes.outputs.any == 'true' }}
    needs: changes
    uses: ./.github/workflows/build-programs.yml
    secrets: inherit

  generate_clients:
    name: Generate clients
    if: ${{ needs.changes.outputs.any == 'true' }}
    needs: build_programs
    runs-on: ubuntu-latest
    outputs:
      js_changed: ${{ steps.changes.outputs.js_client }}
    permissions:
      contents: write
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Node.js
        uses: ./.github/actions/install-node
        with:
          version: ${{ vars.NODE_VERSION }}
          cache: ${{ env.CACHE }}

      - name: Cache IDL generators
        if: env.CACHE == 'true'
        uses: actions/cache@v3
        with:
          path: ./.crates/
          key: ${{ runner.os }}-idl-generators-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-idl-generators

      - name: Generate IDLs and clients
        run: pnpm generate

      - name: Commit generated clients
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update generated clients

      - name: Detect client changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: .github/file-filters.yml

  test_js:
    if: needs.generate_clients.outputs.js_changed == 'true'
    name: JS Client
    needs: generate_clients
    uses: ./.github/workflows/test-js.yml
    secrets: inherit
